### ISSUE TITLE
It was a great tool when it was working, please fix it if you can!

### ISSUE THREAD

**Issue by Alecsasha** [suhailidrees/autotrader_scraper#1]
Hello! The code stopped working recently. It was incredibly useful tool to analyse and understand used car prices in the UK when it was working. If it is something that can be fixed it would be much appreciated.

Thank you

**Comment by suhailidrees** [comment]
Hi Alecsasha,

Thanks for bringing it to my attention! Looks like they added CloudFlare protection and changed the format which affects the scraping methodology.

I've made a few changes in v0.1.1 which fix the issues for me. **Please have a go at updating the package (best way is to uninstall and reinstall using pip) and then trying again.**

Unfortunately I had to use a package that requires Python 3 to bypass CloudFlare so you might need to use a newer Python version.

Let me know how you get on,
Suhail

**Comment by Alecsasha** [comment]
It is back online! Thank you for looking into this and fixing it.
